[package]
name = "mc-rs-generate"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
convert_case = "0.4"
enum_dispatch = "0.3"
env_logger = "0.10"
git2 = "0.18"
itertools = { workspace = true }
json = "0.12"
log = { workspace = true }
mc-rs-extract = { version = "0.1", path = "../mc-rs-extract" }
prettyplease = "0.2"
proc-macro2 = { version = "1.0", features = ["nightly"] }
quote = "1.0"
reqwest = { version = "0.11", features = ["rustls-tls", "json", "blocking"], default-features = false }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
strum = { workspace = true }
syn = { version = "2.0", features = ["extra-traits"] }
tempfile = { version = "3", features = ["nightly"] }
zip = { version = "0.6", features = ["flate2"] }

