[package]
name = "mc-rs-world"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[lints]
workspace = true

[dependencies]
azalea-nbt = { workspace = true }
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
bitvec = "1.0"
compact_str = { workspace = true }
derive_more = { workspace = true }
futures-lite = { workspace = true }
mc-rs-core = { version = "0.1", path = "../mc-rs-core" }
mc-rs-macros = { version = "0.1", path = "../mc-rs-macros" }
mc-rs-protocol = { version = "0.1", path = "../mc-rs-protocol" }
mc-rs-resourcepack = { version = "0.1", path = "../mc-rs-resourcepack" }
parking_lot = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }

[features]
default = []

# Enable debug features
debug = ["mc-rs-macros/debug", "mc-rs-core/debug", "mc-rs-protocol/debug", "mc-rs-resourcepack/debug"]

# Enable simd features
simd = ["mc-rs-core/simd", "mc-rs-protocol/simd", "mc-rs-resourcepack/simd", "bevy_rapier3d/simd-stable"]
