[package]
name = "mc-rs-interface"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"
build = "build.rs"

[build-dependencies]
vergen = { version = "8.2.5", features = ["build", "cargo", "git", "gitoxide"] }

[dependencies]
bevy = { workspace = true, features = ["serialize"] }
compact_str = { workspace = true }
leafwing-input-manager = "0.10.0"
mc-rs-core = { version = "0.1.0", path = "../mc-rs-core" }
mc-rs-render = { version = "0.1.0", path = "../mc-rs-render" }
rand = { version = "0.8", features = ["nightly"] }
serde = { workspace = true }
strum = { workspace = true }
toml = "0.8"

[features]
default = ["splash"]
splash = []

# Enable debug features
debug = []

# Enable simd features
simd = ["mc-rs-core/simd", "mc-rs-render/simd"]
# !! Currently broken on the latest nightly !!
simd_advanced = ["mc-rs-core/simd_advanced", "mc-rs-render/simd_advanced", "rand/simd_support"]
