[package]
name = "mc-rs-interface"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"
build = "build.rs"

[build-dependencies]
vergen = { version = "8.2", features = ["build", "cargo", "git", "gitoxide"] }

[dependencies]
anyhow = "1.0"
bevy = { workspace = true, features = ["serialize"] }
compact_str = { workspace = true }
dirs = "5.0"
mc-rs-core = { version = "0.1", path = "../mc-rs-core" }
rand = { version = "0.8", features = ["nightly"] }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = "1.0"
toml = "0.8"
zip = { version = "0.6", features = ["flate2"] }

[features]
default = []

# Enable debug features
debug = ["mc-rs-core/debug", "bevy/embedded_watcher", "bevy/file_watcher"]
# Enable bevy-rapier debug features
debug_rapier = ["mc-rs-core/debug_rapier"]

# Enable wayland features
wayland = ["bevy/wayland"]

# Enable simd features
simd = ["mc-rs-core/simd"]
# !! Currently broken on the latest nightly !!
simd_advanced = ["mc-rs-core/simd_advanced", "rand/simd_support"]
