[package]
name = "mc-rs-interface"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
azalea-nbt = { version = "0.8.0", git = "https://github.com/EightFactorial/azalea.git", branch = "nbt", default-features = false }
belly = { version = "0.3.0", git = "https://github.com/EightFactorial/belly.git" }
bevy = "0.11"
log = { version = "0.4", features = ["std"] }
mc-rs-core = { version = "0.1.0", path = "../mc-rs-core" }
rand = { version = "0.8", features = ["nightly"] }
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
toml = "0.8"

[features]
default = ["splash"]
splash = []

# Enable debug features
debug = []

# Enable simd features
simd = ["mc-rs-core/simd"]
# !! Currently broken on the latest nightly !!
simd_advanced = ["mc-rs-core/simd_advanced", "rand/simd_support"]
