# Define the custom order of derive attributes.
order = ["Debug", "Default", "Clone", "Copy" , "PartialEq", "Eq", "PartialOrd", "Ord", "Hash", "...", "Serialize", "Deserialize", "Facet"]

# Preserve the original order for unspecified derive attributes
preserve = true
