# --- Version Configuration --- #
#
# Versions grouped together must have the same protocol version!
#
# [[version]]
# base = "1.20.0" # Name of the supported version
# jar = "1.20.1" # Jar used to generate code

[[version]]
base = "1.21.0"
jar = "1.21.1"

[[version]]
base = "1.21.2"
jar = "1.21.2"
