[package]
name = "mc-rs-macros"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[lib]
proc-macro = true

[features]
debug = []

[dependencies]
attribute-derive = "0.8"
convert_case = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
strum = { workspace = true }
syn = "2.0"
