[package]
name = "mc-rs-render"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.11"
bevy_rapier3d = { version = "0.22.0", features = ["parallel"] }
bytemuck = { version = "1.14", features = ["derive"] }
futures-lite = { version = "2.0", features = ["futures-io"] }
itertools = "0.11"
mc-rs-core = { version = "0.1.0", path = "../mc-rs-core" }
ndshape = "0.3"

[features]
default = []

# Enable debug features
debug = []

# Enable simd features
simd = []
# !! Currently broken on the latest nightly !!
simd_advanced = []
