[package]
name = "mc-rs-proto"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[dependencies]
async-compression = { version = "0.4.1", features = ["futures-io", "zlib"] }
async-net = "1.7.0"
azalea-chat = { version = "0.7.0", default-features = false }
azalea-nbt = { git = "https://github.com/EightFactorial/azalea", branch = "nbt", default-features = false }
bevy_ecs = "0.11.2"
bevy_math = "0.11.2"
byteorder = { version = "1.4.3", features = ["i128"] }
derive_more = "0.99.17"
futures-lite = { version = "1.13.0", features = ["futures-io"] }
hashbrown = { version = "0.14.0", features = ["serde"], optional = true }
log = { version = "0.4.19", features = ["std"], optional = true}
mc-rs-macros = { path = "../mc-rs-macros" }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = { version = "1.0.103", features = ["preserve_order", "arbitrary_precision"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.43"
uuid = { version = "1.4.1", features = ["v3"] }


[features]
default = ["hashbrown"]
hashbrown = ["dep:hashbrown"]
debug = ["dep:log", "mc-rs-macros/debug"]