[package]
name = "mc-rs-proto"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[dependencies]
async-std = "1.12.0"
bevy_ecs = "0.11.0"
bevy_derive = "0.11.0"
mc-rs-macros = { path = "../mc-rs-macros" }
thiserror = "1.0.43"
uuid = { version = "1.4.1", features = ["v3"] }
byteorder = { version = "1.4.3", features = ["i128"] }
strum = { version = "0.25.0", features = ["derive"] }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = { version = "1.0.103", features = ["preserve_order", "arbitrary_precision"] }
hashbrown = { version = "0.14.0", features = ["serde"], optional = true }

[features]
default = ["hashbrown"]
hashbrown = ["dep:hashbrown"]