[package]
name = "mc-rs-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-chat = { version = "0.8.0", default-features = false }
azalea-nbt = { version = "0.8.0", git = "https://github.com/EightFactorial/azalea.git", branch = "nbt", default-features = false }
bevy = { version = "0.11", features = ["serialize"] }
bevy_rapier3d = { version = "0.22.0", features = ["parallel"] }
block-mesh = "0.2.0"
bytemuck = { version = "1.14", features = ["derive"] }
compact_str = { version = "0.7", features = ["serde", "smallvec"] }
futures-lite = { version = "1.13", features = ["futures-io"] }
itertools = "0.11"
log = { version = "0.4", features = ["std"] }
mc-rs-protocol = { version = "0.1.0", path = "../mc-rs-protocol" }
nohash-hasher = "0.2"
parking_lot = { version = "0.12", features = ["nightly"] }
rand = { version = "0.8", features = ["nightly"] }
uuid = "1.5"

[features]
default = ["splash"]
splash = []

# Enable debug features
debug = ["mc-rs-protocol/debug"]

# Enable simd features
simd = ["bevy_rapier3d/simd-stable"]
# !! Currently broken on the latest nightly !!
simd_advanced = ["bevy_rapier3d/simd-nightly", "rand/simd_support"]

