[package]
name = "mc-rs-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[dependencies]
azalea-chat = { version = "0.8.0", default-features = false }
azalea-nbt = { version = "0.8.0", git = "https://github.com/EightFactorial/azalea.git", branch = "nbt", default-features = false }
bevy = "0.11"
bevy_rapier3d = { version = "0.22.0", features = ["parallel"] }
compact_str = "0.7"
log = { version = "0.4", features = ["std"] }
mc-rs-protocol = { version = "0.1.0", path = "../mc-rs-protocol" }
nohash-hasher = "0.2"
parking_lot = { version = "0.12", features = ["nightly"] }
uuid = "1.5"

[features]
default = ["simd"]


# Enable debug features
debug = ["mc-rs-protocol/debug"]
# Enable bevy-rapier3d debug features
debug_rapier = []

# Enable simd features
simd = ["mc-rs-protocol/simd", "bevy_rapier3d/simd-stable"]
# !! Currently broken on the latest nightly !!
simd_advanced = ["mc-rs-protocol/simd_advanced", "bevy_rapier3d/simd-nightly"]

