[package]
name = "mc-rs-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[lints]
workspace = true

[dependencies]
azalea-chat = { workspace = true }
bevy = { workspace = true }
compact_str = { workspace = true }
mc-rs-protocol = { version = "0.1", path = "../mc-rs-protocol" }
nohash-hasher = "0.2"
parking_lot = { version = "0.12", features = ["nightly"] }
uuid = { workspace = true }

[features]
default = ["simd"]

# Enable debug features
debug = ["mc-rs-protocol/debug"]

# Enable simd features
simd = ["mc-rs-protocol/simd", "azalea-chat/simdnbt"]
