[package]
name = "mc-rs-protocol"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[dependencies]
async-compression = { version = "0.4", features = ["futures-io", "zlib"] }
async-net = "1.8"
azalea-chat = { workspace = true }
azalea-nbt = { workspace = true }
bevy_ecs = "0.11"
bevy_math = "0.11"
byteorder = "1.5"
compact_str = { workspace = true }
derive_more = { workspace = true }
futures-lite = { workspace = true }
hashbrown = { version = "0.14", features = ["serde"] }
log = { workspace = true, optional = true }
mc-rs-macros = { version = "0.1.0", path = "../mc-rs-macros" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order", "arbitrary_precision"] }
smallvec = { workspace = true }
strum = { workspace = true }
thiserror = "1.0"
uuid = { workspace = true, features = ["v3"] }

[dev-dependencies]
pretty_assertions = "1.4"

[features]
default = []

# Enable debug features
debug = ["dep:log", "mc-rs-macros/debug"]

# Enable simd features
simd = []
# !! Currently broken on the latest nightly !!
simd_advanced = []
