[package]
name = "mc-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"
build = "build.rs"

[build-dependencies]
vergen = { version = "8.2.4", features = ["build", "cargo", "git", "gitoxide"]}

[dependencies]
anyhow = "1.0.72"
async-net = "1.7.0"
async-trait = "0.1.72"
azalea-chat = { version = "0.7.0", default-features = false }
azalea-nbt = { git = "https://github.com/EightFactorial/azalea", branch = "nbt", default-features = false }
belly = { git = "https://github.com/EightFactorial/belly" }
bevy = { version = "0.11.0", features = ["serialize"] }
bevy_rapier3d = { version = "0.22.0", features = ["parallel"] }
block-mesh = "0.2.0"
convert_case = "0.6.0"
flume = "0.10.14"
futures-lite = { version = "1.13.0", features = ["futures-io"] }
futures-locks = { version = "0.7.1", default-features = false }
itertools = "0.11.0"
log = { version = "0.4.19", features = ["std"] }
mc-rs-proto = { path = "../mc-rs-proto" }
mc-rs-macros = { path = "../mc-rs-macros" }
noise = { version = "0.8.2", features = ["std", "image"] }
rand = { version = "0.8.5", features = ["nightly"] }
serde = { version = "1.0.179", features = ["derive"] }
strum = { version = "0.25.0", features = ["derive"] }
toml = { version = "0.7.6", features = ["preserve_order"] }
uuid = { version = "1.4.1", features = ["v3"] }

[features]
default = ["wayland", "splash"]
splash = []
simd = ["bevy_rapier3d/simd-nightly", "rand/packed_simd"]

# Enable bevy features
wayland = ["bevy/wayland"]

# Enable debug plugins
debug = ["mc-rs-proto/debug", "mc-rs-macros/debug", "bevy_rapier3d/debug-render-3d"]
