[package]
name = "mc-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"
build = "build.rs"

[build-dependencies]
vergen = { version = "8.2.4", features = ["build", "cargo", "git", "gitoxide"]}

[dependencies]
belly = { git = "https://github.com/jkb0o/belly.git", branch = "bevy-0.11" }
bevy = { version = "0.11.0", features = ["serialize"] }
bevy_rapier3d = { version = "0.22.0", features = ["simd-nightly", "debug-render-3d"] }
futures-lite = { version = "1.13.0", features = ["futures-io"] }
mc-rs-proto = { path = "../mc-rs-proto" }
mc-rs-macros = { path = "../mc-rs-macros" }
noise = { version = "0.8.2", features = ["std", "image"] }
rand = { version = "0.8.5", features = ["packed_simd", "nightly"] }
serde = { version = "1.0.179", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v3"] }
toml = { version = "0.7.6", features = ["preserve_order"] }
log = { version = "0.4.19", features = ["std"] }

[features]
default = ["wayland", "splash"]
splash = []

# Enable bevy features
wayland = ["bevy/wayland"]
