[package]
name = "mc-rs-extract"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[lib]
name = "mc_rs_extract"
path = "src/lib.rs"

[[bin]]
name = "mc_rs_extract"
path = "src/bin/main.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
classfile-rs = { version = "0.1", path = "../classfile-rs" }
derive_more = { workspace = true }
enum_dispatch = "0.3"
env_logger = "0.10"
hashbrown = { version = "0.14", features = ["serde"] }
itertools = { workspace = true }
json = "0.12"
log = { workspace = true }
reqwest = { version = "0.11", features = ["rustls", "json", "blocking"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
strum = { workspace = true }
thiserror = "1.0"
zip = "0.6"
