[package]
name = "mc-rs-network"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["EightFactorial"]
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[dependencies]
bevy = { workspace = true }
compact_str = { workspace = true }
flume = "0.11"
futures-lite = { workspace = true }
futures-locks = { version = "0.7", default-features = false }
mc-rs-core = { version = "0.1.0", path = "../mc-rs-core" }
mc-rs-protocol = { version = "0.1.0", path = "../mc-rs-protocol" }

[features]
default = []

# Enable debug features
debug = ["mc-rs-core/debug", "mc-rs-protocol/debug"]

# Enable simd features
simd = ["mc-rs-core/simd", "mc-rs-protocol/simd"]
# !! Currently broken on the latest nightly !!
simd_advanced = ["mc-rs-core/simd_advanced", "mc-rs-protocol/simd_advanced"]
