[package]
name = "mc-rs-ext"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/EightFactorial/MC-RS"
repository = "https://github.com/EightFactorial/MC-RS"
readme = "README.md"

[lib]
name = "mc_rs_ext"
path = "src/lib.rs"

[[bin]]
name = "mc_rs_ext"
path = "src/bin/main.rs"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.17", features = ["derive"] }
classfile-rs = { path = "../classfile-rs" }
derive_more = "0.99.17"
env_logger = "0.10.0"
hashbrown = "0.14.0"
log = { version = "0.4.19", features = ["std"] }
reqwest = { version = "0.11.18", features = ["rustls", "json", "blocking"] }
serde = { version = "1.0.173", features = ["derive"] }
serde_json = { version = "1.0.103", features = ["preserve_order"] }
thiserror = "1.0.43"
zip = "0.6.6"

[features]
