name: Spellcheck

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SAT"

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      # Run Spellcheck and write fixes
      - name: Spellcheck (Fix)
        id: spellcheck-fix
        uses: crate-ci/typos@master
        with: 
          write_changes: true
        continue-on-error: true
      # Run Spellcheck and verify fixes
      - name: Spellcheck (Verify)
        id: spellcheck-verify
        if: steps.spellcheck-fix.outcome != 'success'
        uses: crate-ci/typos@master
      # Create PR with fixes
      - name: Pull Request
        if: steps.spellcheck-fix.outcome != 'success' && steps.spellcheck-verify.outcome == 'success'
        uses: peter-evans/create-pull-request@v6.1.0
